// tslint:disable
/**
 * GeoServer Namespace
 * A namespace is a uniquely identifiable grouping of feature types. It is identified by a prefix and a URI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: geoserver-users@sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
