// tslint:disable
/**
 * GeoServer Fonts
 * A font is a set of characters that can be used in a style for displaying labels.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: geoserver-users@sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface FontListItem
 */
export interface FontListItem {
    /**
     * Name of font
     * @type {string}
     * @memberof FontListItem
     */
    entry?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Invalid. Fonts cannot be deleted through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFonts: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/fonts`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Displays a list of all fonts on the server. You must use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/fonts.xml\" for XML)
         * @summary Get a list of fonts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFonts: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/fonts`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalid. Fonts cannot be added through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postFonts: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/fonts`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalid. Fonts cannot be updated through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putFonts: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/fonts`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Invalid. Fonts cannot be deleted through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFonts(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).deleteFonts(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Displays a list of all fonts on the server. You must use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/fonts.xml\" for XML)
         * @summary Get a list of fonts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFonts(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FontListItem>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).getFonts(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Invalid. Fonts cannot be added through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postFonts(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).postFonts(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Invalid. Fonts cannot be updated through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putFonts(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).putFonts(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Invalid. Fonts cannot be deleted through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFonts(options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).deleteFonts(options).then((request) => request(axios, basePath));
        },
        /**
         * Displays a list of all fonts on the server. You must use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/fonts.xml\" for XML)
         * @summary Get a list of fonts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFonts(options?: any): AxiosPromise<Array<FontListItem>> {
            return DefaultApiFp(configuration).getFonts(options).then((request) => request(axios, basePath));
        },
        /**
         * Invalid. Fonts cannot be added through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postFonts(options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).postFonts(options).then((request) => request(axios, basePath));
        },
        /**
         * Invalid. Fonts cannot be updated through the REST API.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putFonts(options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).putFonts(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
    /**
     * Invalid. Fonts cannot be deleted through the REST API.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteFonts(options?: any): AxiosPromise<void>;

    /**
     * Displays a list of all fonts on the server. You must use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/fonts.xml\" for XML)
     * @summary Get a list of fonts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFonts(options?: any): AxiosPromise<Array<FontListItem>>;

    /**
     * Invalid. Fonts cannot be added through the REST API.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postFonts(options?: any): AxiosPromise<void>;

    /**
     * Invalid. Fonts cannot be updated through the REST API.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    putFonts(options?: any): AxiosPromise<void>;

}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * Invalid. Fonts cannot be deleted through the REST API.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteFonts(options?: any) {
        return DefaultApiFp(this.configuration).deleteFonts(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Displays a list of all fonts on the server. You must use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/fonts.xml\" for XML)
     * @summary Get a list of fonts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getFonts(options?: any) {
        return DefaultApiFp(this.configuration).getFonts(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalid. Fonts cannot be added through the REST API.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postFonts(options?: any) {
        return DefaultApiFp(this.configuration).postFonts(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalid. Fonts cannot be updated through the REST API.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public putFonts(options?: any) {
        return DefaultApiFp(this.configuration).putFonts(options).then((request) => request(this.axios, this.basePath));
    }

}


