// tslint:disable
/**
 * GeoServer WMS Stores
 * A WMS store is a store whose source is another WMS. Also known as \"Cascading WMS\" or \"Exernal WMS\".
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: geoserver-users@sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface WMSStoreInfo
 */
export interface WMSStoreInfo {
    /**
     * Name of the WMS store
     * @type {string}
     * @memberof WMSStoreInfo
     */
    name?: string;
    /**
     * Description of the WMS store
     * @type {string}
     * @memberof WMSStoreInfo
     */
    description?: string;
    /**
     * Type of store. Set to WMS.
     * @type {string}
     * @memberof WMSStoreInfo
     */
    type?: string;
    /**
     * Whether the store is enabled
     * @type {boolean}
     * @memberof WMSStoreInfo
     */
    enabled?: boolean;
    /**
     * 
     * @type {WMSStoreInfoWorkspace}
     * @memberof WMSStoreInfo
     */
    workspace?: WMSStoreInfoWorkspace;
    /**
     * 
     * @type {WMSStoreInfoMetadata}
     * @memberof WMSStoreInfo
     */
    metadata?: WMSStoreInfoMetadata;
    /**
     * Whether the store is the default store of the workspace
     * @type {boolean}
     * @memberof WMSStoreInfo
     */
    __default__?: boolean;
    /**
     * Location of the WMS capabilities URL where the store originates
     * @type {string}
     * @memberof WMSStoreInfo
     */
    capabilitiesURL?: string;
    /**
     * User name to use when connecting to the remote WMS
     * @type {string}
     * @memberof WMSStoreInfo
     */
    user?: string;
    /**
     * Password or hash to use when connecting to the remote WMS
     * @type {string}
     * @memberof WMSStoreInfo
     */
    password?: string;
    /**
     * Maximum number of simultaneous connections to use
     * @type {number}
     * @memberof WMSStoreInfo
     */
    maxConnections?: number;
    /**
     * Time in seconds before read time out
     * @type {string}
     * @memberof WMSStoreInfo
     */
    readTimeout?: string;
    /**
     * Time in seconds before connection time out
     * @type {string}
     * @memberof WMSStoreInfo
     */
    connectTimeout?: string;
    /**
     * 
     * @type {Array<WMSStoreInfoWmsLayers>}
     * @memberof WMSStoreInfo
     */
    wmsLayers?: Array<WMSStoreInfoWmsLayers>;
}
/**
 * Miscellaneous configuration details about the WMS store
 * @export
 * @interface WMSStoreInfoMetadata
 */
export interface WMSStoreInfoMetadata {
    /**
     * 
     * @type {WMSStoreInfoMetadataEntry}
     * @memberof WMSStoreInfoMetadata
     */
    entry?: WMSStoreInfoMetadataEntry;
}
/**
 * 
 * @export
 * @interface WMSStoreInfoMetadataEntry
 */
export interface WMSStoreInfoMetadataEntry {
    /**
     * Set to useConnectionPooling
     * @type {string}
     * @memberof WMSStoreInfoMetadataEntry
     */
    key?: WMSStoreInfoMetadataEntryKeyEnum;
    /**
     * Whether connection pooling is enabled
     * @type {boolean}
     * @memberof WMSStoreInfoMetadataEntry
     */
    text?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum WMSStoreInfoMetadataEntryKeyEnum {
    UseConnectionPooling = 'useConnectionPooling'
}

/**
 * 
 * @export
 * @interface WMSStoreInfoWmsLayers
 */
export interface WMSStoreInfoWmsLayers {
    /**
     * Link to the WMS layers representation
     * @type {string}
     * @memberof WMSStoreInfoWmsLayers
     */
    link?: string;
}
/**
 * Workspace containing the store
 * @export
 * @interface WMSStoreInfoWorkspace
 */
export interface WMSStoreInfoWorkspace {
    /**
     * Name of the workspace
     * @type {string}
     * @memberof WMSStoreInfoWorkspace
     */
    name: string;
    /**
     * Link to the workspace representation
     * @type {string}
     * @memberof WMSStoreInfoWorkspace
     */
    link?: string;
}
/**
 * 
 * @export
 * @interface WMSStoresListItem
 */
export interface WMSStoresListItem {
    /**
     * Name of WMS Store
     * @type {string}
     * @memberof WMSStoresListItem
     */
    name?: string;
    /**
     * URL to WMS store representation
     * @type {string}
     * @memberof WMSStoresListItem
     */
    link?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deletes a WMS store
         * @summary Delete WMS store
         * @param {string} workspace Name of the workspace containing the WMS store.
         * @param {string} store Name of the WMS store
         * @param {boolean} [recurse] When set to true all resources contained in the store are also removed.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWMSStore: async (workspace: string, store: string, recurse?: boolean, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspace' is not null or undefined
            if (workspace === null || workspace === undefined) {
                throw new RequiredError('workspace','Required parameter workspace was null or undefined when calling deleteWMSStore.');
            }
            // verify required parameter 'store' is not null or undefined
            if (store === null || store === undefined) {
                throw new RequiredError('store','Required parameter store was null or undefined when calling deleteWMSStore.');
            }
            const localVarPath = `/workspaces/{workspace}/wmsstores/{store}`
                .replace(`{${"workspace"}}`, encodeURIComponent(String(workspace)))
                .replace(`{${"store"}}`, encodeURIComponent(String(store)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (recurse !== undefined) {
                localVarQueryParameter['recurse'] = recurse;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalid. Use /workspaces/{workspace}/wmsstores/{wmsstore} instead.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWMSStores: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/workspaces/{workspace}/wmsstores`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Displays a representation of the WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/workspaces/{workspace}/wmsstores/{store}.xml\" for XML). Defaults to HTML representation.
         * @summary Retrieve a WMS store in a given workspace
         * @param {string} workspace The name of the workspace containing the WMS store.
         * @param {string} store The name of the store to be retrieved
         * @param {boolean} [quietOnNotFound] When set to true, avoids to log an Exception when the WMS store is not present. Note that 404 status code will be returned anyway.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWMSStore: async (workspace: string, store: string, quietOnNotFound?: boolean, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspace' is not null or undefined
            if (workspace === null || workspace === undefined) {
                throw new RequiredError('workspace','Required parameter workspace was null or undefined when calling getWMSStore.');
            }
            // verify required parameter 'store' is not null or undefined
            if (store === null || store === undefined) {
                throw new RequiredError('store','Required parameter store was null or undefined when calling getWMSStore.');
            }
            const localVarPath = `/workspaces/{workspace}/wmsstores/{store}`
                .replace(`{${"workspace"}}`, encodeURIComponent(String(workspace)))
                .replace(`{${"store"}}`, encodeURIComponent(String(store)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (quietOnNotFound !== undefined) {
                localVarQueryParameter['quietOnNotFound'] = quietOnNotFound;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Displays a list of all WMS stores on the server. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/rest/workspaces/{workspace}/wmsstores.xml\" for XML).
         * @summary Get a list of WMS stores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWMSStores: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/workspaces/{workspace}/wmsstores`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalid. Use POST on /workspaces/{workspace}/WMSstores for adding a new WMS store, or PUT on /workspaces/{workspace}/WMSstores/{store} to edit/upload an existing WMS store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWMSStore: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/workspaces/{workspace}/wmsstores/{store}`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Adds a new WMS store entry to the server.
         * @summary Add a new WMS store
         * @param {string} workspace Name of the worskpace containing the WMS store.
         * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;name&gt;remote&lt;/name&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;name\&quot;: \&quot;remote\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;     }   }   &#x60;&#x60;&#x60; 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWMSStores: async (workspace: string, wMSStoreBody: WMSStoreInfo, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspace' is not null or undefined
            if (workspace === null || workspace === undefined) {
                throw new RequiredError('workspace','Required parameter workspace was null or undefined when calling postWMSStores.');
            }
            // verify required parameter 'wMSStoreBody' is not null or undefined
            if (wMSStoreBody === null || wMSStoreBody === undefined) {
                throw new RequiredError('wMSStoreBody','Required parameter wMSStoreBody was null or undefined when calling postWMSStores.');
            }
            const localVarPath = `/workspaces/{workspace}/wmsstores`
                .replace(`{${"workspace"}}`, encodeURIComponent(String(workspace)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/xml';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof wMSStoreBody !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(wMSStoreBody !== undefined ? wMSStoreBody : {}) : (wMSStoreBody || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modifies a single WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"{store}.xml\" for XML).
         * @summary Modify a single WMS store.
         * @param {string} workspace The name of the worskpace containing the WMS stores.
         * @param {string} store The name of the store to be retrieved
         * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload. For a PUT, only values which should be changed need to be included.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;description&gt;A wms store&lt;/description&gt;     &lt;enabled&gt;true&lt;/enabled&gt;     &lt;__default&gt;true&lt;/__default&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;     &lt;user&gt;admin&lt;/user&gt;     &lt;password&gt;geoserver&lt;/password&gt;     &lt;maxConnections&gt;6&lt;/maxConnections&gt;     &lt;readTimeout&gt;60&lt;/readTimeout&gt;     &lt;connectTimeout&gt;30&lt;/connectTimeout&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;description\&quot;: \&quot;A wms store\&quot;,       \&quot;enabled\&quot;: \&quot;true\&quot;,       \&quot;_default\&quot;: \&quot;true\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;,       \&quot;user\&quot;: \&quot;admin\&quot;,       \&quot;password\&quot;: \&quot;geoserver\&quot;,       \&quot;maxConnections\&quot;: \&quot;6\&quot;,       \&quot;readTimeout\&quot;: \&quot;60\&quot;,       \&quot;connectTimeout\&quot;: \&quot;30\&quot;     }   }   &#x60;&#x60;&#x60; 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putWMSStore: async (workspace: string, store: string, wMSStoreBody: WMSStoreInfo, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspace' is not null or undefined
            if (workspace === null || workspace === undefined) {
                throw new RequiredError('workspace','Required parameter workspace was null or undefined when calling putWMSStore.');
            }
            // verify required parameter 'store' is not null or undefined
            if (store === null || store === undefined) {
                throw new RequiredError('store','Required parameter store was null or undefined when calling putWMSStore.');
            }
            // verify required parameter 'wMSStoreBody' is not null or undefined
            if (wMSStoreBody === null || wMSStoreBody === undefined) {
                throw new RequiredError('wMSStoreBody','Required parameter wMSStoreBody was null or undefined when calling putWMSStore.');
            }
            const localVarPath = `/workspaces/{workspace}/wmsstores/{store}`
                .replace(`{${"workspace"}}`, encodeURIComponent(String(workspace)))
                .replace(`{${"store"}}`, encodeURIComponent(String(store)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/xml';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof wMSStoreBody !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(wMSStoreBody !== undefined ? wMSStoreBody : {}) : (wMSStoreBody || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalid. Use POST for adding a new WMS store, or PUT on /workspaces/{workspace}/wmsstores/{wmsstore} to edit an existing WMS store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putWMSStores: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/workspaces/{workspace}/wmsstores`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Deletes a WMS store
         * @summary Delete WMS store
         * @param {string} workspace Name of the workspace containing the WMS store.
         * @param {string} store Name of the WMS store
         * @param {boolean} [recurse] When set to true all resources contained in the store are also removed.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWMSStore(workspace: string, store: string, recurse?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).deleteWMSStore(workspace, store, recurse, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Invalid. Use /workspaces/{workspace}/wmsstores/{wmsstore} instead.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWMSStores(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).deleteWMSStores(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Displays a representation of the WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/workspaces/{workspace}/wmsstores/{store}.xml\" for XML). Defaults to HTML representation.
         * @summary Retrieve a WMS store in a given workspace
         * @param {string} workspace The name of the workspace containing the WMS store.
         * @param {string} store The name of the store to be retrieved
         * @param {boolean} [quietOnNotFound] When set to true, avoids to log an Exception when the WMS store is not present. Note that 404 status code will be returned anyway.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWMSStore(workspace: string, store: string, quietOnNotFound?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WMSStoreInfo>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).getWMSStore(workspace, store, quietOnNotFound, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Displays a list of all WMS stores on the server. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/rest/workspaces/{workspace}/wmsstores.xml\" for XML).
         * @summary Get a list of WMS stores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWMSStores(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WMSStoresListItem>>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).getWMSStores(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Invalid. Use POST on /workspaces/{workspace}/WMSstores for adding a new WMS store, or PUT on /workspaces/{workspace}/WMSstores/{store} to edit/upload an existing WMS store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postWMSStore(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).postWMSStore(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Adds a new WMS store entry to the server.
         * @summary Add a new WMS store
         * @param {string} workspace Name of the worskpace containing the WMS store.
         * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;name&gt;remote&lt;/name&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;name\&quot;: \&quot;remote\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;     }   }   &#x60;&#x60;&#x60; 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postWMSStores(workspace: string, wMSStoreBody: WMSStoreInfo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).postWMSStores(workspace, wMSStoreBody, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Modifies a single WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"{store}.xml\" for XML).
         * @summary Modify a single WMS store.
         * @param {string} workspace The name of the worskpace containing the WMS stores.
         * @param {string} store The name of the store to be retrieved
         * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload. For a PUT, only values which should be changed need to be included.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;description&gt;A wms store&lt;/description&gt;     &lt;enabled&gt;true&lt;/enabled&gt;     &lt;__default&gt;true&lt;/__default&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;     &lt;user&gt;admin&lt;/user&gt;     &lt;password&gt;geoserver&lt;/password&gt;     &lt;maxConnections&gt;6&lt;/maxConnections&gt;     &lt;readTimeout&gt;60&lt;/readTimeout&gt;     &lt;connectTimeout&gt;30&lt;/connectTimeout&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;description\&quot;: \&quot;A wms store\&quot;,       \&quot;enabled\&quot;: \&quot;true\&quot;,       \&quot;_default\&quot;: \&quot;true\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;,       \&quot;user\&quot;: \&quot;admin\&quot;,       \&quot;password\&quot;: \&quot;geoserver\&quot;,       \&quot;maxConnections\&quot;: \&quot;6\&quot;,       \&quot;readTimeout\&quot;: \&quot;60\&quot;,       \&quot;connectTimeout\&quot;: \&quot;30\&quot;     }   }   &#x60;&#x60;&#x60; 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putWMSStore(workspace: string, store: string, wMSStoreBody: WMSStoreInfo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).putWMSStore(workspace, store, wMSStoreBody, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Invalid. Use POST for adding a new WMS store, or PUT on /workspaces/{workspace}/wmsstores/{wmsstore} to edit an existing WMS store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putWMSStores(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).putWMSStores(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Deletes a WMS store
         * @summary Delete WMS store
         * @param {string} workspace Name of the workspace containing the WMS store.
         * @param {string} store Name of the WMS store
         * @param {boolean} [recurse] When set to true all resources contained in the store are also removed.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWMSStore(workspace: string, store: string, recurse?: boolean, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).deleteWMSStore(workspace, store, recurse, options).then((request) => request(axios, basePath));
        },
        /**
         * Invalid. Use /workspaces/{workspace}/wmsstores/{wmsstore} instead.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWMSStores(options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).deleteWMSStores(options).then((request) => request(axios, basePath));
        },
        /**
         * Displays a representation of the WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/workspaces/{workspace}/wmsstores/{store}.xml\" for XML). Defaults to HTML representation.
         * @summary Retrieve a WMS store in a given workspace
         * @param {string} workspace The name of the workspace containing the WMS store.
         * @param {string} store The name of the store to be retrieved
         * @param {boolean} [quietOnNotFound] When set to true, avoids to log an Exception when the WMS store is not present. Note that 404 status code will be returned anyway.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWMSStore(workspace: string, store: string, quietOnNotFound?: boolean, options?: any): AxiosPromise<WMSStoreInfo> {
            return DefaultApiFp(configuration).getWMSStore(workspace, store, quietOnNotFound, options).then((request) => request(axios, basePath));
        },
        /**
         * Displays a list of all WMS stores on the server. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/rest/workspaces/{workspace}/wmsstores.xml\" for XML).
         * @summary Get a list of WMS stores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWMSStores(options?: any): AxiosPromise<Array<WMSStoresListItem>> {
            return DefaultApiFp(configuration).getWMSStores(options).then((request) => request(axios, basePath));
        },
        /**
         * Invalid. Use POST on /workspaces/{workspace}/WMSstores for adding a new WMS store, or PUT on /workspaces/{workspace}/WMSstores/{store} to edit/upload an existing WMS store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWMSStore(options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).postWMSStore(options).then((request) => request(axios, basePath));
        },
        /**
         * Adds a new WMS store entry to the server.
         * @summary Add a new WMS store
         * @param {string} workspace Name of the worskpace containing the WMS store.
         * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;name&gt;remote&lt;/name&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;name\&quot;: \&quot;remote\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;     }   }   &#x60;&#x60;&#x60; 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWMSStores(workspace: string, wMSStoreBody: WMSStoreInfo, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).postWMSStores(workspace, wMSStoreBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Modifies a single WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"{store}.xml\" for XML).
         * @summary Modify a single WMS store.
         * @param {string} workspace The name of the worskpace containing the WMS stores.
         * @param {string} store The name of the store to be retrieved
         * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload. For a PUT, only values which should be changed need to be included.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;description&gt;A wms store&lt;/description&gt;     &lt;enabled&gt;true&lt;/enabled&gt;     &lt;__default&gt;true&lt;/__default&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;     &lt;user&gt;admin&lt;/user&gt;     &lt;password&gt;geoserver&lt;/password&gt;     &lt;maxConnections&gt;6&lt;/maxConnections&gt;     &lt;readTimeout&gt;60&lt;/readTimeout&gt;     &lt;connectTimeout&gt;30&lt;/connectTimeout&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;description\&quot;: \&quot;A wms store\&quot;,       \&quot;enabled\&quot;: \&quot;true\&quot;,       \&quot;_default\&quot;: \&quot;true\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;,       \&quot;user\&quot;: \&quot;admin\&quot;,       \&quot;password\&quot;: \&quot;geoserver\&quot;,       \&quot;maxConnections\&quot;: \&quot;6\&quot;,       \&quot;readTimeout\&quot;: \&quot;60\&quot;,       \&quot;connectTimeout\&quot;: \&quot;30\&quot;     }   }   &#x60;&#x60;&#x60; 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putWMSStore(workspace: string, store: string, wMSStoreBody: WMSStoreInfo, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).putWMSStore(workspace, store, wMSStoreBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Invalid. Use POST for adding a new WMS store, or PUT on /workspaces/{workspace}/wmsstores/{wmsstore} to edit an existing WMS store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putWMSStores(options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).putWMSStores(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
    /**
     * Deletes a WMS store
     * @summary Delete WMS store
     * @param {string} workspace Name of the workspace containing the WMS store.
     * @param {string} store Name of the WMS store
     * @param {boolean} [recurse] When set to true all resources contained in the store are also removed.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteWMSStore(workspace: string, store: string, recurse?: boolean, options?: any): AxiosPromise<void>;

    /**
     * Invalid. Use /workspaces/{workspace}/wmsstores/{wmsstore} instead.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteWMSStores(options?: any): AxiosPromise<void>;

    /**
     * Displays a representation of the WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/workspaces/{workspace}/wmsstores/{store}.xml\" for XML). Defaults to HTML representation.
     * @summary Retrieve a WMS store in a given workspace
     * @param {string} workspace The name of the workspace containing the WMS store.
     * @param {string} store The name of the store to be retrieved
     * @param {boolean} [quietOnNotFound] When set to true, avoids to log an Exception when the WMS store is not present. Note that 404 status code will be returned anyway.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getWMSStore(workspace: string, store: string, quietOnNotFound?: boolean, options?: any): AxiosPromise<WMSStoreInfo>;

    /**
     * Displays a list of all WMS stores on the server. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/rest/workspaces/{workspace}/wmsstores.xml\" for XML).
     * @summary Get a list of WMS stores
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getWMSStores(options?: any): AxiosPromise<Array<WMSStoresListItem>>;

    /**
     * Invalid. Use POST on /workspaces/{workspace}/WMSstores for adding a new WMS store, or PUT on /workspaces/{workspace}/WMSstores/{store} to edit/upload an existing WMS store.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postWMSStore(options?: any): AxiosPromise<void>;

    /**
     * Adds a new WMS store entry to the server.
     * @summary Add a new WMS store
     * @param {string} workspace Name of the worskpace containing the WMS store.
     * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;name&gt;remote&lt;/name&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;name\&quot;: \&quot;remote\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;     }   }   &#x60;&#x60;&#x60; 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postWMSStores(workspace: string, wMSStoreBody: WMSStoreInfo, options?: any): AxiosPromise<void>;

    /**
     * Modifies a single WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"{store}.xml\" for XML).
     * @summary Modify a single WMS store.
     * @param {string} workspace The name of the worskpace containing the WMS stores.
     * @param {string} store The name of the store to be retrieved
     * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload. For a PUT, only values which should be changed need to be included.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;description&gt;A wms store&lt;/description&gt;     &lt;enabled&gt;true&lt;/enabled&gt;     &lt;__default&gt;true&lt;/__default&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;     &lt;user&gt;admin&lt;/user&gt;     &lt;password&gt;geoserver&lt;/password&gt;     &lt;maxConnections&gt;6&lt;/maxConnections&gt;     &lt;readTimeout&gt;60&lt;/readTimeout&gt;     &lt;connectTimeout&gt;30&lt;/connectTimeout&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;description\&quot;: \&quot;A wms store\&quot;,       \&quot;enabled\&quot;: \&quot;true\&quot;,       \&quot;_default\&quot;: \&quot;true\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;,       \&quot;user\&quot;: \&quot;admin\&quot;,       \&quot;password\&quot;: \&quot;geoserver\&quot;,       \&quot;maxConnections\&quot;: \&quot;6\&quot;,       \&quot;readTimeout\&quot;: \&quot;60\&quot;,       \&quot;connectTimeout\&quot;: \&quot;30\&quot;     }   }   &#x60;&#x60;&#x60; 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    putWMSStore(workspace: string, store: string, wMSStoreBody: WMSStoreInfo, options?: any): AxiosPromise<void>;

    /**
     * Invalid. Use POST for adding a new WMS store, or PUT on /workspaces/{workspace}/wmsstores/{wmsstore} to edit an existing WMS store.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    putWMSStores(options?: any): AxiosPromise<void>;

}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * Deletes a WMS store
     * @summary Delete WMS store
     * @param {string} workspace Name of the workspace containing the WMS store.
     * @param {string} store Name of the WMS store
     * @param {boolean} [recurse] When set to true all resources contained in the store are also removed.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteWMSStore(workspace: string, store: string, recurse?: boolean, options?: any) {
        return DefaultApiFp(this.configuration).deleteWMSStore(workspace, store, recurse, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalid. Use /workspaces/{workspace}/wmsstores/{wmsstore} instead.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteWMSStores(options?: any) {
        return DefaultApiFp(this.configuration).deleteWMSStores(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Displays a representation of the WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/workspaces/{workspace}/wmsstores/{store}.xml\" for XML). Defaults to HTML representation.
     * @summary Retrieve a WMS store in a given workspace
     * @param {string} workspace The name of the workspace containing the WMS store.
     * @param {string} store The name of the store to be retrieved
     * @param {boolean} [quietOnNotFound] When set to true, avoids to log an Exception when the WMS store is not present. Note that 404 status code will be returned anyway.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getWMSStore(workspace: string, store: string, quietOnNotFound?: boolean, options?: any) {
        return DefaultApiFp(this.configuration).getWMSStore(workspace, store, quietOnNotFound, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Displays a list of all WMS stores on the server. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"/rest/workspaces/{workspace}/wmsstores.xml\" for XML).
     * @summary Get a list of WMS stores
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getWMSStores(options?: any) {
        return DefaultApiFp(this.configuration).getWMSStores(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalid. Use POST on /workspaces/{workspace}/WMSstores for adding a new WMS store, or PUT on /workspaces/{workspace}/WMSstores/{store} to edit/upload an existing WMS store.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postWMSStore(options?: any) {
        return DefaultApiFp(this.configuration).postWMSStore(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Adds a new WMS store entry to the server.
     * @summary Add a new WMS store
     * @param {string} workspace Name of the worskpace containing the WMS store.
     * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;name&gt;remote&lt;/name&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;name\&quot;: \&quot;remote\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;     }   }   &#x60;&#x60;&#x60; 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postWMSStores(workspace: string, wMSStoreBody: WMSStoreInfo, options?: any) {
        return DefaultApiFp(this.configuration).postWMSStores(workspace, wMSStoreBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modifies a single WMS store. Use the \"Accept:\" header to specify format or append an extension to the endpoint (example \"{store}.xml\" for XML).
     * @summary Modify a single WMS store.
     * @param {string} workspace The name of the worskpace containing the WMS stores.
     * @param {string} store The name of the store to be retrieved
     * @param {WMSStoreInfo} wMSStoreBody WMS store body information to upload. For a PUT, only values which should be changed need to be included.  Examples: - application/xml:    &#x60;&#x60;&#x60;   &lt;wmsStore&gt;     &lt;description&gt;A wms store&lt;/description&gt;     &lt;enabled&gt;true&lt;/enabled&gt;     &lt;__default&gt;true&lt;/__default&gt;     &lt;capabilitiesUrl&gt;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities&lt;/capabilitiesUrl&gt;     &lt;user&gt;admin&lt;/user&gt;     &lt;password&gt;geoserver&lt;/password&gt;     &lt;maxConnections&gt;6&lt;/maxConnections&gt;     &lt;readTimeout&gt;60&lt;/readTimeout&gt;     &lt;connectTimeout&gt;30&lt;/connectTimeout&gt;   &lt;/wmsStore&gt;   &#x60;&#x60;&#x60;  - application/json:    &#x60;&#x60;&#x60;   {     \&quot;wmsStore\&quot;: {       \&quot;description\&quot;: \&quot;A wms store\&quot;,       \&quot;enabled\&quot;: \&quot;true\&quot;,       \&quot;_default\&quot;: \&quot;true\&quot;,       \&quot;capabilitiesUrl\&quot;: \&quot;http://demo.geoserver.org/geoserver/wms?SERVICE&#x3D;WMS&amp;VERSION&#x3D;1.1.1&amp;REQUEST&#x3D;GetCapabilities\&quot;,       \&quot;user\&quot;: \&quot;admin\&quot;,       \&quot;password\&quot;: \&quot;geoserver\&quot;,       \&quot;maxConnections\&quot;: \&quot;6\&quot;,       \&quot;readTimeout\&quot;: \&quot;60\&quot;,       \&quot;connectTimeout\&quot;: \&quot;30\&quot;     }   }   &#x60;&#x60;&#x60; 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public putWMSStore(workspace: string, store: string, wMSStoreBody: WMSStoreInfo, options?: any) {
        return DefaultApiFp(this.configuration).putWMSStore(workspace, store, wMSStoreBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalid. Use POST for adding a new WMS store, or PUT on /workspaces/{workspace}/wmsstores/{wmsstore} to edit an existing WMS store.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public putWMSStores(options?: any) {
        return DefaultApiFp(this.configuration).putWMSStores(options).then((request) => request(this.axios, this.basePath));
    }

}


